name: Be SOMEBODY

on: issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '🚀 Thanks for the feedback. Things are happening for us now. We are all going to BE SOMEBODY!! Cheers, Klaw. 🚀'
        pr-message: '🚀 Thanks for the pull request. Things are happening for us now. We are all going to BE SOMEBODY!! Cheers, Klaw. 🚀'
