name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for the feedback. We'll take a look. Cheers, Klaw.'
        pr-message: 'Thanks for the pull request. Cheers, Klaw.'
